spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cultureevents
    username: postgres
    password: culture
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate #validate на проде
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080
